name: Main Branch Publish

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    paths:
      - '.github/workflows/build-main.yml'
      - 'build/**'
      - 'scripts/**'
      - 'SD Next/**'
      - 'workspace/**'
      - 'docker-bake.hcl'
      - 'Dockerfile'
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - cu118
          - cu120
          - cu121
          - cu122
          - cu123
          - cu124
          - cu125
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          targets: ${{ matrix.target }}
          provenance: false