name: Dev Branch Publish

on:
  push:
    paths-ignore:
      - '.github/workflows/build-main.yml'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
    branches:
      - 'dev'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nvidia:
    name: Build Nvidia CUDA Image 
    uses: ./.github/workflows/cuda.yml
    with:
      CHANNEL: dev-
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  rocm:
    name: Build AMD ROCm Image
    uses: ./.github/workflows/rocm.yml
    with:
      CHANNEL: dev-
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}