name: Main Branch Publish

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  checkTag:
    name: Check Current/Previous Tag
    runs-on: ubuntu-latest
    outputs:
      current: ${{github.ref_name}}
      previous: ${{steps.previoustag.outputs.PREVIOUS_TAG}}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: 'Get Previous Tag'
        id: previoustag
        run: echo "PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_OUTPUT

  nvidia:
    needs: [checkTag]
    name: Build Nvidia CUDA Image 
    uses: ./.github/workflows/cuda.yml
    with:
      CURRENT_TAG: ${{needs.checkTag.outputs.current}}
      PREVIOUS_TAG: ${{needs.checkTag.outputs.previous}}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  rocm:
    needs: [checkTag]
    name: Build AMD ROCm Image
    uses: ./.github/workflows/rocm.yml
    with:
      CURRENT_TAG: ${{needs.checkTag.outputs.current}}
      PREVIOUS_TAG: ${{needs.checkTag.outputs.previous}}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}