name: ROCm Build

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  workflow_call:
    inputs:
      CHANNEL:
        required: false
        type: string
      CURRENT_TAG:
        required: false
        type: string
        default: "0.0.0"
      PREVIOUS_TAG:
        required: false
        type: string
        default: "0.0.0"
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  build:
    name: Build Start
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - rocm5-5
          - rocm5-6
          - rocm5-7
          - rocm6-0
          - rocm6-1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Create HCL Override
        run: echo -e "VERSION=\"${{inputs.CURRENT_TAG}}\"\nPREVIOUS_VERSION=\"${{inputs.PREVIOUS_TAG}}\"" > env.hcl
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          targets: "${{ inputs.CHANNEL }}${{ matrix.target }}"
          provenance: false
          files: env.hcl, docker-bake.rocm.hcl